### ISSUE TITLE
Secure Gravatar URLs

### ISSUE THREAD

**Issue by razza12** [bentideswell/magento1-wordpress-integration#1]
https://github.com/bentideswell/magento1-wordpress-integration/blob/cd05053717c574913f071cceb5065643651e35f3/app/code/community/Fishpig/Wordpress/Model/User.php#L211-L214

Can this be made to respect secure websites (as is done for the comment model).

**Comment by bentideswell** [comment]
This is good request. I have just pushed version 4.5.0.17 which does this.
