### ISSUE TITLE
Recoverable error

### ISSUE THREAD

**Issue by Axel29** [bentideswell/magento1-wordpress-integration#2]
Hello,

I noticed a bug on some pages using FishPig:

Recoverable Error: Object of class Mage_Core_Model_Translate_Expr could not be converted to string  in app/code/community/Fishpig/Wordpress/Model/Translate.php on line 58

**Comment by bentideswell** [comment]
Can you provide more info on how to recreate this? Are you using the latest version of all FishPig modules? If not, please upgrade and retest. If the issue persists, please send over steps to recreate the issue.
