### ISSUE TITLE
Sitemap - inject wrong domain at multistore multisite setup

### ISSUE THREAD

**Issue by Motomotors** [bentideswell/magento1-wordpress-integration#4]
Hello,

I noticed if you have Magento multistore and Wordpress multisite setup, then wrong blog urls are injected to the Magento sitemaps at cron generation. The post urls in the first store's sitemap is good, but all urls in the following sitemaps uses the urls belong to first store.

This caused by this part of code in file app/code/community/Fishpig/Wordpress/Helper/Abstract.php in getWpOption function:
`
...
$cacheKey = 'wp_option_' . $key;

if ($this->_isCached($cacheKey)) {
	return $this->_cached($cacheKey);
}

$this->_cache($cacheKey, $default);

try {
	$select = $db->select()
	->from(Mage::getSingleton('core/resource')->getTableName('wordpress/option'), 'option_value')
	->where('option_name = ?', $key)
	->limit(1);
...
`
In Wordpress multisite setup you have different table prefix for each site, and this way above caches the options for the very first store and all the following sitemaps use that.

I solved the problem by change the above code to:
`
...
$wp_table = Mage::getSingleton('core/resource')->getTableName('wordpress/option');

$cacheKey = $wp_table . '_' . $key;

if ($this->_isCached($cacheKey)) {
	return $this->_cached($cacheKey);
}

$this->_cache($cacheKey, $default);

try {
	$select = $db->select()
		->from($wp_table, 'option_value')
		->where('option_name = ?', $key)
		->limit(1);
...
`

It's quite problematic to rewrite an abstract class, so it would be nice if it could be fixed officially :)

**Comment by bentideswell** [comment]
Are you sure you're using the latest versions of the modules? I believe this issue was fixed with an upgrade.

**Comment by Motomotors** [comment]
Yepp, I checked now, the problem persists in 4.6.1.21.

**Comment by bentideswell** [comment]
I wasn't able to recreate the issue but I've released an update that includes your fix so hopefully that solves the issue for you.
